[package]
name = "enclave-usercalls"
version = "0.2.0"
authors = ["Jethro Beekman <jethro@fortanix.com>"]

[target.'cfg(target_os="none")'.dependencies]
enclave = { version = "0.1", path = "../libenclave" }
