[workspace]

[package]
name = "get-certificate"
version = "0.1.0"
authors = ["fortanix.com"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
em-app = { path = "../../" }
mbedtls = { git = "https://github.com/fortanix/rust-mbedtls.git", branch = "acruceru/wip-mbed-hyper-v2", default-features = false, features = ["sgx"]}
serde_json = "1.0"