[package]
name = "enclave-example-runner"
description = "Example program using a secure enclave"
version = "0.1.1"
authors = ["Jethro Beekman <jethro@jbeekman.nl>"]
license = "GPL-2.0+"
repository = "https://github.com/jethrogb/sgx-utils/tree/master/enclave-example"

[[bin]]
name = "enclave-runner"

[dependencies]
"sgxs" = "0.5.0"
"sgx-isa" = "0.1.0"
"enclave-interface" = "0.1.1" # Check the libenclave/enclave-interface version
                              # compatibility chart when modifying this version
