[package]
name = "enclave-example-runner"
description = "Example program using a secure enclave"
version = "0.1.1"
authors = ["Jethro Beekman <jethro@jbeekman.nl>"]
license = "GPL-2.0+"
repository = "https://github.com/jethrogb/sgx-utils/tree/master/enclave-example"

[[bin]]
name = "enclave-runner"

[dependencies]
"sgxs" = { path = "../../sgxs" }
"sgx-isa" = { path = "../../sgx-isa" }
# Check the libenclave/enclave-interface version compatibility chart when
# choosing a version of enclave-interface.
enclave-interface = { path = "../../enclave-interface"}
enclave-example-usercalls = { path = "../usercalls" }
libc = "0.2.12"
