[package]
name = "enclave-example"
description = "Example secure enclave written in Rust"
version = "0.1.3"
authors = ["Jethro Beekman <jethro@jbeekman.nl>"]
license = "AGPL-3.0+"
repository = "https://github.com/jethrogb/sgx-utils/tree/master/enclave-example"

[dependencies]
"sgx-isa" = { path = "../../sgx-isa" }
# The version of `enclave` should be the same as the version of
# libenclave-tools you use to build. Also check the
# libenclave/enclave-interface version compatibility chart
enclave = { path = "../../libenclave" }
enclave-example-usercalls = { path = "../usercalls" }

[features]
enclave_debug = ["enclave/debug"]
